# Generated by Django 4.2.3 on 2023-08-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=10000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mg', models.IntegerField(default='0')),
            ],
        ),
    ]
