# Generated by Django 4.2.3 on 2023-08-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_post_username_post_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
    ]
